services:
  manipulation:
    container_name: home2-manipulation
    build:
      context: ../..
      dockerfile: docker/manipulation/Dockerfile.l4t
      args:
        BASE_IMAGE: roborregos/home2:l4t_base
    image: roborregos/home2:manipulation-l4t
    volumes:
      - ../../:/workspace/src/
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./build/:/workspace/build
      - ./install/:/workspace/install
      - ./log/:/workspace/log
      - ../frida_interfaces_cache:/workspace/frida_interfaces_cache
      - ./.bash_aliases:/home/ros/.bash_aliases
      - ./setup_gpd.sh:/home/ros/setup_gpd.sh

    network_mode: host
    user: ${LOCAL_USER_ID}:${LOCAL_GROUP_ID}
    privileged: true
    runtime: nvidia
    group_add: 
      - video
    environment:
      DISPLAY: :0
      TERM: xterm-256color
      QT_X11_NO_MITSHM: 1
      QT_DEBUG_PLUGINS: 1
    tty: true
    stdin_open: true    
    working_dir: /workspace
    command: >    
      bash -c "${COMMAND:-/bin/bash}"