services:
  display:
    container_name: home2-hri-display-l4t
    image: roborregos/home2:hri-display-l4t
    build:
      context: ../../..
      dockerfile: docker/hri/dockerfiles/Dockerfile.display
      args:
        BASE_IMAGE: roborregos/home2:l4t_base
    volumes:
      - ../../../hri/display/:/app
      - /dev:/dev
    network_mode: host
    command: ["/bin/bash", "/display-entrypoint.sh"]
