services:
  ollama:
    profiles: [receptionist, carry, gpsr, storing]
    container_name: home2-hri-ollama-cuda
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ollama
    image: roborregos/home2:hri-ollama-cuda
    runtime: nvidia
    network_mode: host
    volumes:
      - ../scripts/ollama:/ollama
    environment:
      OLLAMA_MODELS: /ollama
      ROLE: ${ROLE}
    stdin_open: true
    tty: true
    entrypoint:
      ["/bin/bash", "-c", "/ollama/entrypoint.sh && tail -f /dev/null"]
