services:
  ollama:
    profiles: [receptionist, carry, gpsr, storing]
    container_name: home2-hri-ollama-cuda
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ollama
    image: roborregos/home2:hri-ollama-cuda
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../../hri/packages/nlp/assets:/ollama
    environment:
      OLLAMA_MODELS: /ollama
      ROLE: ${ROLE}
    stdin_open: true
    tty: true
    entrypoint:
<<<<<<< HEAD
      ["/bin/bash", "-c", "/ollama/entrypoint.sh && tail -f /dev/null"]
=======
      ["/bin/bash", "-c", "/scripts/entrypoint.sh && tail -f /dev/null"]
>>>>>>> 53eaec2f433ebaf3acc49743c2903ceb6f00d99c
