services:
  ollama:
    profiles: [hric, carry, gpsr, storing]
    container_name: home2-hri-ollama-l4t
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.ollama
      args:
        BASE_IMAGE: dustynv/ollama:0.6.8-r36.4
    image: roborregos/home2:hri-ollama-l4t
    runtime: nvidia
    network_mode: host
    volumes:
      - ../../../hri/packages/nlp/assets:/ollama
    environment:
      OLLAMA_MODELS: /ollama
      ROLE: ${ROLE}
    stdin_open: true
    tty: true
    entrypoint:
      ["/bin/bash", "-c", "/scripts/entrypoint.sh && tail -f /dev/null"]
