services:
  postgres:
    image: roborregos/home2:hri-postgres-${ENV_TYPE:-cpu}
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.postgres
    container_name: home2-hri-postgres-${ENV_TYPE:-cpu}
    restart: "no"
    environment:
      POSTGRES_USER: rbrgs
      POSTGRES_PASSWORD: rbrgs
      POSTGRES_DB: postgres
    network_mode: host
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
