services:
  stt:
    profiles: [hric, carry, gpsr, storing]
    container_name: home2-hri-stt-l4t
    image: roborregos/home2:hri-stt-l4t
    runtime: nvidia
    build:
      context: ../../..
      dockerfile: docker/hri/dockerfiles/Dockerfile.stt-l4t
    volumes:
      - ../../../hri/packages/speech/scripts/stt/:/app
      - ../../../hri/packages/speech/speech/:/app/speech
    network_mode: host
    # Any language -> english: distil-large-v3
    # Any language -> Any language: large-v3-turbo
    command: >
      bash -c "source /tmp/PyAV/scripts/activate.sh && deactivate && python3 -u faster-whisper-streaming.py --port 50051 --model distil-large-v3 --log_transcriptions"
